name: 'Build and deploy a Compute@Edge project'
author: Fastly
description: 'Build and deploy a Compute@Edge package using the Fastly CLI.'

branding:
  icon: 'cloud-lightning'
  color: 'red'

inputs:
  project_directory:
    description: 'Directory of the project to deploy, relative to the repository root.'
    required: false
    default: './'
  cli_version:
    description: 'The version of the Fastly CLI to install, e.g. v0.20.0'
    required: false
    default: 'latest'
  service_id:
    description: 'The Fastly service ID to deploy to. Defaults to the value in fastly.toml'
    required: false
    default: 'default'
  comment:
    description: 'An optional comment to be included with the deployed service version.'
    required: false
    default: ''
  verbose:
    description: 'Set to true to enable verbose logging'
    required: false
    default: 'false'
  skip_verification:
    description: 'Skip verification steps before build.'
    required: false
    default: 'false'
  token:
    description: 'The GitHub token to use when interacting with the GitHub API'
    required: false
    default: 'false'

runs:
  using: node12
  pre: setup/index.js
  main: build/index.js
  post: deploy/index.js
