name: 'Setup the Fastly CLI for Compute'
author: 'Fastly'
description: 'Downloads and configures the Fastly CLI and Viceroy.'

branding:
  icon: 'settings'
  color: 'red'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  cli_version:
    description: 'The version of the Fastly CLI to install, e.g. v0.1.0'
    required: false
    default: 'latest'
  viceroy_version:
    description: 'The version of Viceroy to install, e.g. v0.1.0'
    required: false
    default: 'latest'
  token:
    description: 'The GitHub token to use when interacting with the GitHub API'
    required: false
