name: 'Setup the Fastly CLI for Compute@Edge'
author: 'Fastly'
description: 'Downloads and configures the Fastly CLI.'

branding:
  icon: 'settings'
  color: 'red'

runs:
  using: 'node12'
  main: 'index.js'

inputs:
  cli_version:
    description: 'The version of the Fastly CLI to install, e.g. v1.0.0'
    required: false
    default: 'latest'
